python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/blackswan/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/bmx-trees/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/breakdance/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/camel/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/car-roundabout/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/car-shadow/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/cows/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/dance-twirl/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/dog/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/drift-chicane/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/drift-straight/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/goat/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/horsejump-high/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/kite-surf/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/libby/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/motocross-jump/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/paragliding-launch/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/parkour/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/scooter-black/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
python nlc_online.py -imdir /home/eren/Data/DAVIS/JPEGImages/480p/soapbox/ -out /home/eren/Data/DAVIS/Motion_nlc/ -maxsp 400 -iters 100
