python main.py configs/DAVIS16_online 0
python main.py configs/DAVIS16_online 1
python main.py configs/DAVIS16_online 2
python main.py configs/DAVIS16_online 3
python main.py configs/DAVIS16_online 4
python main.py configs/DAVIS16_online 5
python main.py configs/DAVIS16_online 6
python main.py configs/DAVIS16_online 7
python main.py configs/DAVIS16_online 8
python main.py configs/DAVIS16_online 9
python main.py configs/DAVIS16_online 11
python main.py configs/DAVIS16_online 12
python main.py configs/DAVIS16_online 13
python main.py configs/DAVIS16_online 16
